---
- name: Package Management
  hosts: "{{ MachineGroupName }}"
  become: yes
  become_method: runas
  become_user: System
  gather_facts: no
  vars_files:
    - CommonVars/FileManagement_Vars.yml
  vars:
    trimcount: "4"

  tasks:
    - name: Get Package Name
      set_fact:
        PackageName: "{{ PackageFileName | regex_replace('.{' + trimcount + '}$', '') }}"

    - name: Download package {{PackageFileName}} from Ansible controller machine to servers
      win_copy:
        src: "{{ PackageSourceLocation }}/{{PackageFileName}}"
        dest: "{{ PackageDestinationLocation }}"
        remote_src: no

    - name: Extract package {{PackageFileName}} to {{PackageUnzipLocation}}
      win_unzip:
        src: "{{PackageDestinationLocation}}\\{{PackageFileName}}"
        dest: "{{PackageUnzipLocation}}\\{{PackageName}}"
        delete_archive: yes