---
- name: PlatformCode deployment
  hosts: "{{MachineGroupName}}"
  become: yes
  become_method: runas
  become_user: System
  gather_facts: yes
  vars_files:
   - CommonVars/PlatformCode_LAN.yml
   - CommonVars/UserCredentials.yml

  ######## Pre deployement steps ########

  pre_tasks:

    
    ######## Take backup of CC_Runtime folder ######## 

    - name: Take backup of {{PlatformCodeModuleName}} folder
      win_shell: Copy-Item "{{ RemoteHost_CC_Runtime_Folder_Path }}" -Destination {{BackupFolderPath}}\{{PlatformCodeModuleName}}_{{ ansible_date_time.iso8601_basic_short}}\ -Recurse
      
    ######## Take backup of Corecardservices folder ######## 

    - name: Take backup of {{CorecardServicesModuleName}} folder
      win_shell: Copy-Item "{{ RemoteHost_Corecard_Services_Folder_Path }}" -Destination {{BackupFolderPath}}\{{CorecardServicesModuleName}}_{{ ansible_date_time.iso8601_basic_short}}\ -Recurse


    ######## Create Package folder ########

    - name: Create Package folder
      win_file:
        path: "{{PackageFolderPath}}"
        state: directory

    ######## Download PlatformCode package ########

    - name: Download PlatformCode package {{PackageFileName}}{{PackageFileExtension}} from Ansible controller machine to LAN servers
      win_copy:
        src: "{{ PackageSourceLocation }}/{{PackageFileName}}{{PackageFileExtension}}"
        dest: "{{ DestinationFolderPath }}"
        remote_src: no

    
    ######## Extract PlatformCode package ######## 

    - name: Extract {{DestinationFolderPath}} to {{UnzipFolderPath}}
      win_unzip:
        src: "{{DestinationFolderPath}}"
        dest: "{{UnzipFolderPath}}"
        delete_archive: yes
      
    ######## Stop dbbstartup service ########

    - name: Stop dbbstartup service
      win_service:
        name: dbbStartupService
        state: stopped
      register: dbbstartupStatus
      
    ######## Check DbbStartupService state ########

    - name: Check DbbStartupService state 
      debug: 
        var: dbbstartupStatus.state

    ######## Stop SNMP service ########

    - name: Stop SNMP service
      win_service:
        name: SNMP
        state: stopped
      register: SNMPStatus
      
    ######## Check SNMP state ########

    - name: Check SNMP Service state 
      debug: 
        var: SNMPStatus.state

  ########################################################################################################

  ######## Deployement starts ########

  tasks:

    ######## Delete all files from CC_Runtime folder ########

    - name: Delete all files from {{RemoteHost_CC_Runtime_Folder_Path}} folder
      win_file:
        path: "{{RemoteHost_CC_Runtime_Folder_Path}}"
        state: absent
      
    ######## Deploy PlatformCode to CC_Runtime folder ########

    - name: Copy {{PlatformCodeModuleName}} files from {{ UnzipFolderPath }}\{{PlatformCodeModuleName}}\ to {{RemoteHost_CC_Runtime_Folder_Path}} folder
      win_shell: Copy-Item -Path {{ UnzipFolderPath }}\{{PlatformCodeModuleName}} -Destination {{ RemoteHost_CC_Runtime_Folder_Path }} -Recurse
      
    - name: Fetch PlatformCode version
      win_shell: |
        $filePath = "{{ RemoteHost_CC_Runtime_Folder_Path }}\appsys30.dsl"
        $searchString = "Application Release"
        Get-Content -Path $filePath | ForEach-Object {
          if ($_ -like "*$searchString*") 
          {
            $versionRow = $_.Split('\"')[1].Split(' ')[2]
            $versionRow
          }
        }
      register: platformcodeversion

    - name: Verify PlatformCode version
      debug: 
        msg: "PlatformCode version : {{platformcodeversion.stdout | regex_replace('[\\r\\n\\t]+','')}}"
    
    ######## Deploy CorecardServices to Corecard_Services folder ########

    - name: Copy {{CorecardServicesModuleName}} files from {{ UnzipFolderPath }}\{{CorecardServicesModuleName}}\ to {{RemoteHost_Corecard_Services_Folder_Path}} folder
      win_shell: Copy-Item -Path {{ UnzipFolderPath }}\{{CorecardServicesModuleName}}\* -Destination {{ RemoteHost_Corecard_Services_Folder_Path }} -Recurse -Force
      
      
    ######## Deploy PlatformCode to shared path ########

    - name: Copy PlatformCode from {{ UnzipFolderPath }}\{{PlatformCodeModuleName}}\ to {{ NetworkLocation }}
      win_shell: Copy-Item {{ UnzipFolderPath }}\{{PlatformCodeModuleName}}\* -Destination {{ NetworkLocation }} -Recurse -Force
      
    ######## Delete shared memory ########

    - name: Delete shmem.bin from {{SharedMemory_Path}}
      win_file:
        path: "{{SharedMemory_Path}}\\shmem.bin"
        state: absent
      
    ######## Start dbbstartup service ########

    - name: Start dbbstartup service
      win_service:
        name: dbbStartupService
        state: started
        username: '{{UserName}}'
        password: '{{Password}}'
      register: dbbstartupStatus_post_Upgrade
      
    ######## Check dbbstartup status ########

    - name: Check DbbStartupService state 
      debug: 
        var: dbbstartupStatus_post_Upgrade.state

    ######## Start SNMP service ########

    - name: Start SNMP service
      win_service:
        name: SNMP
        state: started
      register: SNMPStatus_post_Upgrade
     
    ######## Check SNMP status ########
    - name: Check SNMP Service state 
      debug: 
        var: SNMPStatus_post_Upgrade.state
    
    
    

    
            
