---
- name: CoreCARD Process Management (Stop)
  hosts: "{{MachineGroupName}}"
  become: yes
  become_method: runas
  become_user: System
  gather_facts: no
  
  tasks:
    
    ######## Stop Service ########
    - name: Stop Process
      win_shell: |
        $Processes = Get-WmiObject -Class Win32_Process -Filter "name='{{item}}'"
        foreach ($process in $processes)
        {
            $returnval = $process.terminate()
            $processid = $process.handle
            if($returnval.returnvalue -eq 0)
            {
                write-host "The process {{item}} `($processid`) terminated successfully"
            }
            else 
            {
                write-host "The process {{item}} `($processid`) termination has some problems"
            }
        }
      loop: "{{ ProcessList }}"
      loop_control:
        loop_var: item
      register: killed_processes
      when: OperationType == "stop"

    - name: Verify Processes
      debug: 
        var: killed_processes
      when: OperationType == "stop"

    ######## Start Process ########
    - name: Start Process
      win_shell: Start-ScheduledTask -TaskName "{{item}}"
      loop: "{{ ScheduledTaskList }}"
      loop_control:
        loop_var: item
      register: start_processes
      when: OperationType == "start"

    - name: Verify Processes
      debug: 
        var: start_processes
      when: OperationType == "start"