---
- name: CoreCARD Process Management (Start)
  hosts: "{{MachineGroupName}}"
  become: yes
  become_method: runas
  become_user: System
  gather_facts: no
  vars_files:
   - CommonVars/UserCredentials_Vars.yml
  
  tasks:
    
    - name: Start ScheduledTask
      win_shell: |
        $tasks = Get-ScheduledTask | Where-Object { $_.TaskName -like "{{item}}" }
        $tasks | ForEach-Object { Start-ScheduledTask -TaskName $_.TaskName }
      loop: "{{ ScheduledTaskList }}"
      loop_control:
        loop_var: item
      register: start_scheduledtask
      when: OperationType == "start"

    - name: Verify ScheduledTask
      debug: 
        var: start_scheduledtask
      when: OperationType == "start"

    - name: Disable ScheduledTask
      win_shell: |
        $tasks = Get-ScheduledTask | Where-Object { $_.TaskName -like "{{item}}" }
        $tasks | ForEach-Object { Disable-ScheduledTask -TaskName $_.TaskName }
      loop: "{{ ScheduledTaskList }}"
      loop_control:
        loop_var: item
      register: disable_scheduledtask
      when: OperationType == "disable"

    - name: Verify ScheduledTask
      debug: 
        var: disable_scheduledtask
      when: OperationType == "disable"

    - name: Enable ScheduledTask
      win_shell: |
        $tasks = Get-ScheduledTask | Where-Object { $_.TaskName -like "{{item}}" }
        $tasks | ForEach-Object { Enable-ScheduledTask -TaskName $_.TaskName }
      loop: "{{ ScheduledTaskList }}"
      loop_control:
        loop_var: item
      register: enable_scheduledtask
      when: OperationType == "enable"

    - name: Verify ScheduledTask
      debug: 
        var: enable_scheduledtask
      when: OperationType == "enable"

    - name: Change ScheduledTask User
      win_shell: |
        $username = "{{ UserType[User_Type].UserName }}"
        $password = "{{ UserType[User_Type].Password }}"
        $tasks = Get-ScheduledTask | Where-Object { $_.TaskName -like "{{item}}" }
        $tasks | ForEach-Object { Set-ScheduledTask -TaskName $_.TaskName -User $username -Password $password }
      loop: "{{ ScheduledTaskList }}"
      loop_control:
        loop_var: item
      register: enable_scheduledtask
      when: OperationType == "changeuser"

    - name: Verify ScheduledTask User
      debug: 
        var: enable_scheduledtask
      when: OperationType == "changeuser"