---
- name: CoreCARD Service Management (Start)
  hosts: "{{MachineGroupName}}"
  become: yes
  become_method: runas
  become_user: System
  gather_facts: no
  vars_files:
   - CommonVars/UserCredentials_Vars.yml
  tasks:
    
    ######## Stop Service ########
    - name: Stop Service
      win_service:
        name: "{{item}}"
        state: stopped
      loop: "{{ ServiceList }}"
      loop_control:
        loop_var: item
      register: stop_service
      when: OperationType == "stopservice" or OperationType == "disableservice"  or OperationType == "changeserviceuser"

    - name: Verify Service
      debug: 
        var: stop_service
      when: OperationType == "stopservice" or OperationType == "disableservice"

    ######## Change Service User ########
    - name: Change Service User
      win_service:
        name: "{{item}}"
        username: "{{UserType[User_Type].UserName}}"
        password: "{{UserType[User_Type].Password}}"
        state: started
      loop: "{{ ServiceList }}"
      loop_control:
        loop_var: item
      register: change_service_user
      when: OperationType == "changeserviceuser"

    ######## Start Service ########
    - name: Start Service
      win_service:
        name: "{{item}}"
        state: started
      loop: "{{ ServiceList }}"
      loop_control:
        loop_var: item
      register: start_service
      when: OperationType == "startservice"

    - name: Verify Service
      debug: 
        var: start_service
      when: OperationType == "startservice"

    ######## Disable Windows Service ########
    - name: Disable Windows Service
      win_shell: Set-Service -Name "{{item}}" -StartupType Disabled
      loop: "{{ ServiceList }}"
      loop_control:
        loop_var: item
      register: disable_service
      when: OperationType == "disableservice"
    
    ######## Set Windows Service to Automatic Start ########
    - name: Set Windows Service to Automatic Start
      win_shell: Set-Service -Name "{{item}}" -StartupType Automatic
      loop: "{{ ServiceList }}"
      loop_control:
        loop_var: item
      register: enable_service
      when: OperationType == "enableservice"