---
- name: VisualCron Management
  hosts: "{{MachineGroupName}}"
  become: yes
  become_method: runas
  become_user: System
  gather_facts: no
  
  tasks:
    
    ######## Deactivate VisualCron job ########
    - name: Deactivate VisualCron job
      win_shell: |
        $Path = "C:\Program Files (x86)\VisualCron\VCCommand\VCCommand.exe"
        $JobName = "{{JobName}}"
        $Arg = "--action activatejob --connectionmode local --name $JobName --username admin"
        Start-Process -FilePath $Path -ArgumentList $Arg -Wait
      register: result
      when: OperationType == "activate"

    - debug:
        var: result
      when: OperationType == "activate"

    ######## Activate VisualCron job ########
    - name: Activate VisualCron job
      win_shell: |
        $Path = "C:\Program Files (x86)\VisualCron\VCCommand\VCCommand.exe"
        $JobName = "{{JobName}}"
        $Arg = "--action deactivatejob --connectionmode local --name $JobName --username admin"
        Start-Process -FilePath $Path -ArgumentList $Arg -Wait
      register: result
      when: OperationType == "deactivate"

    - debug:
        var: result
      when: OperationType == "deactivate"

    ######## Run VisualCron job ########
    - name: Run VisualCron job
      win_shell: |
        $Path = "C:\Program Files (x86)\VisualCron\VCCommand\VCCommand.exe"
        $JobName = "{{JobName}}"
        $Arg = "--action runjob --connectionmode local --name $JobName --username admin"
        Start-Process -FilePath $Path -ArgumentList $Arg -Wait
      register: result
      when: OperationType == "run"

    - debug:
        var: result
      when: OperationType == "run"